### ISSUE TITLE
NotInitializedError: The proper initialization has not occurred.

### ISSUE THREAD

**Issue by gaboesquivel** [EOSIO/demux-js-postgres#65] opened 2019-04-12 16:21 UTC
from 4.0.0 release notes

> The MassiveActionHandler#setupDatabase public method was removed, and its funcitonality was moved to setup (as described above). Additionally, it is no longer required that you call this method before calling handleBlock(), as handleBlock() will automatically call it if it hasn't been called before.

https://github.com/EOSIO/demux-js-postgres/releases/tag/4.0.0

However I keep getting this err msg.

```
No 'init' Migration sequence was provided, nor was a different initSequenceName.No initial migrations have been run.
An error has occured. error is: NotInitializedError: The proper initialization has not occurred. Failed to migrate the postgres database. and stack trace is: NotInitializedError: The proper initialization has not occurred. Failed to migrate the postgres database.
    at MassiveActionHandler.<anonymous> (/opt/application/node_modules/demux-postgres/dist/MassiveActionHandler.js:97:23)
TypeError: Invalid query format.
    at Database.$query (/opt/application/node_modules/massive/node_modules/pg-promise/lib/query.js:104:21)
    at Database.<anonymous> (/opt/application/node_modules/massive/node_modules/pg-promise/lib/query.js:259:23)
    at config.$npm.connect.pool.then.db (/opt/application/node_modules/massive/node_modules/pg-promise/lib/database.js:326:42)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

Cod
```js
  // See https://eosio.github.io/demux-js/ for info on Handler Versions, Updaters, and Effects
  const handlerVersions = require("./handlerVersions") 

  // See https://massivejs.org/docs/connecting for info on massive configuration
  const dbConfig = {
    host: DB_HOST || 'postgres',
    port: DB_PORT || 5432,
    database: DB_NAME || 'postgres',
    user: DB_USER || 'user',
    password: DB_PASSWORD || 'pass'
  }

  const db = await massive(dbConfig)

  const actionReader = new MongoActionReader({
    startAtBlock: headBlockNum,   // startAtBlock: the first block relevant to our application
    onlyIrreversible: false,      // onlyIrreversible: whether or not to only process irreversible blocks
    dbName: MONGO_DB,            // name of the database
    mongoEndpoint: MONGO_URI,    // mongoEndpoint: the url of the mongodb instance
  })

  const actionHandler = new MassiveActionHandler(
    handlerVersions,
    db,
    'demux', // dbSchema
    [] // migration sequences
  )

  // await actionHandler.setup() or await actionHandler.setupDatabase() 

  const actionWatcher = new BaseActionWatcher(actionReader, actionHandler, 500)

  // This must be done before calling watch so the MongoDB connection can be made
  await actionReader.initialize()
  actionWatcher.watch()
```

I'm using

```
  "dependencies": {
    "demux": "^4.0.0",
    "demux-eos": "^4.0.1",
    "demux-postgres": "^4.0.1",
    "eosjs": "20.0.0",
    "massive": "^5.7.7"
  }
```

my full pckg list https://gist.github.com/gaboesquivel/acb8c5c2c06e6be0fa9aad460aa7a2c3

**Comment by flux627** [comment] 2019-04-12 18:11
Hi @gaboesquivel! The problem is that you need at least one `MigrationSequence` when instantiating your `MassiveActionHandler`, named `init`. In this, you should create tables that you will use to populate your data.

It's an error to have no `MigrationSequence`s because without tables, there's no point in using the `MassiveActionHandler` at all.

Closing, but feel free to ask followup questions!

**Closed as completed by flux627** 2019-04-12 18:11 UTC

**Comment by gaboesquivel** [comment] 2019-04-16 13:04
@flux627 I'm still having issues with the latest version.  

It seems there might be a problem with the cyanaudit migration. 

<img width="1369" alt="demux-postgres" src="https://user-images.githubusercontent.com/391270/56211679-9ca2b780-6015-11e9-8daa-f5c240b98a5d.png">

First tried 4.0.1, now I'm using master with npm link with console.log to debug

**Comment by codemaster101** [comment] 2019-08-23 03:38
Hey @flux627 I have downloaded demux-js-postgres. Now I want to make a schema table from that to start the demux. But I don't see in the documentation on how to do this. It just tells me to install demux postgres but doesn't have any follow up instructions, but rather explanations to how things work. Could you please add, or tell me here how am I supposed to run the massive action handler correctly. I am sorry but I am not able to understand

**Comment by codemaster101** [comment] 2019-09-06 06:17
@flux627 could you reopen this issue. 

Even I am getting a not initialized error.

This is my problem:

0

I have been trying to set up demux but I keep on getting this error,

```
{ error: duplicate key value violates unique constraint "pg_namespace_nspname_index"
    at Connection.parseE (/home/nodeos2/demux/node_modules/pg/lib/connection.js:557:11)
    at Connection.parseMessage (/home/nodeos2/demux/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/home/nodeos2/demux/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 236,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (nspname)=(cyanaudit) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'pg_catalog',
  table: 'pg_namespace',
  column: undefined,
  dataType: undefined,
  constraint: 'pg_namespace_nspname_index',
  file: 'nbtinsert.c',
  line: '534',
  routine: '_bt_check_unique' }



 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>X
{"name":"demux","hostname":"dev-eosio-1","pid":18069,"level":50,"err":{"message":"The proper initialization has not occurred. Failed to migrate the postgres database.","name":"NotInitializedError","stack":"NotInitializedError: The proper initialization has not occurred. Failed to migrate the postgres database.\n    at MassiveActionHandler.<anonymous> (/home/nodeos2/demux/node_modules/demux-postgres/dist/MassiveActionHandler.js:103:22)\nerror: duplicate key value violates unique constraint \"pg_namespace_nspname_index\"\n    at Connection.parseE (/home/nodeos2/demux/node_modules/pg/lib/connection.js:557:11)\n    at Connection.parseMessage (/home/nodeos2/demux/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/home/nodeos2/demux/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"},"msg":"The proper initialization has not occurred. Failed to migrate the postgres database.","time":"2019-09-06T04:22:14.504Z","v":0}
{"name":"demux","hostname":"dev-eosio-1","pid":18069,"level":30,"msg":"Indexing unexpectedly paused due to an error.","time":"2019-09-06T04:22:14.505Z","v":0}
```

I have tried a lot of things.

For example:

    I tried running it again: program encounters a deadlock. Solved by deleting the existing database and creating it again.
    Tried deleting the database, schema and creating the database again. Does not work! Get the same issue again.
    Tried deleting the cyanaudit file, does not work, cyanaudit file does not get generated again.

The problem is that demux is connecting to postgres database, as the tables in the database are being created, but it fails to migrate the database.

Not sure why this is happening.

This is my file for running demux:
```

const { BaseActionWatcher } = require("demux");
const { MassiveActionHandler } = require("demux-postgres");
const { NodeosActionReader } = require("demux-eos");
const massive = require("demux-postgres/node_modules/massive");

const handlerVersion = require("./handlerVersions/v1");
const migrationSequences = require("./migrationSequences");

const dbConfig = {
  host: 'localhost',
  port: 5432,
  database: 'eos',
  schema: 'public',
  user: 'postgres',
  password: '',
};

massive(dbConfig).then((db) => {
  const actionReader = new NodeosActionReader({
     startAtBlock: 77770000, 
     onlyIrreversible: false, 
     nodeosEndpoint: "https://api.eosnewyork.io"
  });
  const actionHandler = new MassiveActionHandler(
    [handlerVersion],
    db,
    dbConfig.schema,
    migrationSequences
  );
  const actionWatcher = new BaseActionWatcher(actionReader, actionHandler, 500);
  actionWatcher.watch();
})

```
This is my file for the migrationSequences
```

const { Migration } = require("demux-postgres");

const createTransferTable = new Migration(
     "createTransferTable", // name
     "public", // schema
     "create_transfer_table.sql", // SQL file
);

// MigrationSequence[]
// See: https://github.com/EOSIO/demux-js-postgres/blob/develop/src/interfaces.ts
module.exports = [{
   migrations: [createTransferTable],
  sequenceName: "init"
}];
```

This is my file for the sql
```

CREATE TABLE ${schema~}.transfer (
     id serial PRIMARY KEY,
     txid text,
     act smallint,
     from_ text,
     to_ text,
     amount double precision,
     symbol text,
     memo text
);
```

The database is creating the following tables
```

                 List of relations
 Schema |        Name         |   Type   |  Owner   
--------+---------------------+----------+----------
 public | _block_number_txid  | table    | postgres
 public | _index_state        | table    | postgres
 public | _index_state_id_seq | sequence | postgres
 public | _migration          | table    | postgres
 public | _migration_id_seq   | sequence | postgres
```

Any insights?
